steps:
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/alpine-base:latest', 'library/alpine-base:latest' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/alpine-base:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/anaconda3:5.2.0:latest', 'library/anaconda3:5.2.0' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/anaconda3:5.2.0:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/google-cloud-sdk:latest', 'library/google-cloud-sdk:latest' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/google-cloud-sdk:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/python:2.7:latest', 'library/python:2.7' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/python:2.7:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/python:3.5:latest', 'library/python:3.5' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/python:3.5:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/python:3.6:latest', 'library/python:3.6' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/python:3.6:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/python:3.7:latest', 'library/python:3.7' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/python:3.7:latest']
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ruby:2.5:latest', 'library/ruby:2.5' ]
    timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/ruby:2.5:latest']
